accounts/urls.py
from django.urls import URLPattern, path
from .views import SignUpView
app_name = 'accounts'
urlpatterns= [
    path('signup/', SignUpView.as_view(), name='signup' ),
]

car_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls")),
    path('', include("main.urls" , namespace='main') ),

]  + static(settings.STATIC_URL,document_root= settings.STATIC_ROOT) +\
     static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT) 

main/urls.py
from django.urls import path
from .views import (
    index, 
    car_detail,
    category_filter,
    ProductCreateView, 
    ProductUpdateView,
    ProductDeleteView,
)

app_name = "main"

urlpatterns = [
    path('post/<int:pk>delete',  ProductDeleteView.as_view() , name='post_delete'),
    path('post/<int:pk>edit',  ProductUpdateView.as_view(), name='post_edit'),
    path('post/new/', ProductCreateView.as_view(), name= 'post_new' ),
    path('', index, name="index" ),
    path('product/<int:car_detail>',  car_detail ,name='car_detail'),
    path('category/<int:category_id>',category_filter,   name= 'category_filter'),

]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=55)
    reg_date = models.DateField(auto_now_add=True)
    products_qty = models.PositiveIntegerField(default=0,editable=False)

    class Meta:
        verbose_name = "Kategoriya"
        verbose_name_plural = "Kategoriya"

    def __str__(self):
        return f"{self.name}  Added :{self.reg_date}"   


class Product(models.Model):
    category = models.ForeignKey(Category, db_index=True,  on_delete=models.PROTECT)
    name = models.CharField(verbose_name="Tovar nomi",help_text="dssdf sdjdsjfskdfsdfs dshfj", max_length=355,blank=True)
    text = models.TextField(verbose_name="Tovar xaqida",max_length=8000,default="Text yo'q")
    view = models.PositiveIntegerField(verbose_name="Ko'rishlar soni",default=0,editable=False )
    likes = models.PositiveIntegerField(default=0,editable=False)
    dislikes = models.PositiveIntegerField(default=0,editable=False)
    image = models.ImageField(upload_to="")
    reg_date = models.DateField(auto_now_add=True)
    tel_raqam=models.PositiveIntegerField(default=0,editable=True)
    

    class Meta:
        verbose_name = "Tovar"
        verbose_name_plural = "Tovarlar"

    def __str__(self):
        return self.name    
    
    def get_absolute_url(self):
        return reverse('car_detail', args=[str(self.id)])




class Comment(models.Model):
    article = models.ForeignKey(Product,on_delete=models.CASCADE)
    incomment = models.ForeignKey("Comment",on_delete=models.CASCADE,null=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField()
    reg_date = models.DateField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUpView(generic.CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy('login')
    template_name='registration/signup.html'

main/views.py
from dataclasses import field, fields
from re import template
from sre_constants import SUCCESS
from unicodedata import category
from django.shortcuts import render
from .models import Category,Product
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from django.urls import reverse_lazy

# Create your views here.

def index(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {"categories":categories, "products":products}
    return render(request, "index.html", context)

def car_detail(request, car_detail):
    a = Product.objects.get(id = car_detail)
    context ={'Product' : a}
    return render(request, 'car_detail.html' , context)

def category_filter(request, category_id):
    category = Category.objects.get(id = category_id)
    categories= Category.objects.all()
    products = Product.objects.filter(category = category)
    context ={'categories' : categories, 'products':products}
    return render(request, 'index.html' , context)

class ProductCreateView(CreateView):
    model=Product
    template_name='post_new.html'
    fields=['category', 'name', 'text', 'image'] 
    success_url = '/'

    def post(self, request, *args, **kwargs):
        print(3313131)
        print(request.POST)
        return super().post(request, *args, **kwargs)

class ProductUpdateView(UpdateView):
    model=Product
    template_name='post_edit.html'
    fields=['name', 'text', 'image','tel_raqam']
    success_url = '/'

class ProductDeleteView(DeleteView):
    model=Product
    template_name='post_delete.html'
    fields=['name', 'text', 'image','tel_raqam']
    # success_url = reverse_lazy('index')
    success_url = '/'

templates/car_detail.html
<div class="post-entry">
    <h2>{{ Product.name }}</h2>
    <h3>{{ Product.reg_date }}</h3>
    <P>{{ Product.text }}</P>

</div>
<a href="{% url 'main:post_edit' Product.id %}">post tahrirlash</a> <br>
<a href="{% url 'main:post_delete' Product.id %}">postni o`chirish</a>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Shop</title>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
</head>
<body>
  <header>
    <h1><a href="{% url 'main:index' %}">Bosh sahifa</a></h1>
  </header>
  {% if user.is_authenticated %}
  <p> Xush kwlinsiz, {{user.username }}!</p>
  <p><a href="{% url 'log out' %}"> chiqib ketish</a></p>
  {% else %}
  <p>
    <a href="{% url 'login' %}">Saytga kirish </a>
   
  </p>
  {% endif %}

    <nav class="navbar navbar-expand-lg navbar-light bg-success">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      <div class="container mt-5">
          <div class="row">

              <div class="col-md-9">
                  <img src="/static/images/31.jpg" width="100%" alt="">
              </div>
              <div class="col-md-3">
                <ul class="list-group">
                  <li class="list-group-item"> 
                    <a href="/"> Hamma kategoriyalar  </a>
                 </li>
                    {% for c in categories %}
                    <li class="list-group-item"> 
                       <a href="/category/{{ c.id }}">  {{ c.name }} </a>
                    </li>
                   {% endfor %}
                  </ul>
                  
              </div>
          </div>
      </div>


    <div class="container mt-5">
        <div class="row">

        {% for product in products %}
        <div class="col-md-4">
            <div class="card">
                <h1> {{ product.name }}  </h1>
                <img src="{{ product.image.url }}" style="width: 300px; height: 250px;" alt="Article image">
                <p> {{ product.text }} </p>
                
                <h2>Qo'shigan sanasi : {{ product.reg_date }} </h2>
                <a href="/product/{{ product.id }}" class="btn btn-success">Batafsil o'qish</a>
            </div>
        </div>
        {% endfor %}


        </div>
    </div>
    <footer>
      <h2><a href="{% url 'main:post_new' %}">+Yangi qo`shish</a></h2>
    </footer>



      
    
</body>
</html>

templates/post_delete.html
{% block content %}
    <h1>postni o`chirish</h1>
    <form action="" method="post">{% csrf_token %}
        <p>"{{ Product.name }}" postni o`chiraymi </p>
    <input type="submit" value="o`chirish">
    </form>
{% endblock content %}

templates/post_edit.html
{% block content %}
    <h1>Postni Taxrirlash</h1>
    <form action="" method="post"  enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Yangilash">
    </form>
{% endblock content %}
 

templates/post_new.html
{% block content %}
    <h1>Yangi qo`shish</h1>
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        sdsd
        <input type="submit" value="saqlash">
    </form>
{% endblock content %}